# Generated by Django 5.2.1 on 2025-09-10 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/images/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва матеріалу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('file', 'Файл'), ('image', 'Зображення'), ('link', 'Посилання'), ('youtube', 'YouTube Відео')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження'),
        ),
        migrations.AlterField(
            model_name='material',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='Посилання'),
        ),
    ]
