# Generated by Django 5.2.4 on 2025-08-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='calendar_image'),
        ),
    ]
