# Generated by Django 5.2.4 on 2025-08-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_question_test_choice_question_test_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='choice_img'),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
