# Generated by Django 5.2.4 on 2025-09-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0003_choice_img_choice_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='choice_img', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильний варіант'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Варіант відповіді:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Питання:'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис тесту:'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва тесту:'),
        ),
    ]
